### ISSUE TITLE
enable to specify arguments of TeXcount

### ISSUE THREAD

**Issue by shuntaroy** [Aerijo/latex-wordcount#2]
Thank you for your great package!

I wish I could pass arbitrary arguments to TeXcount from settings, or other solutions like showing input window when executing.
For example, TeXcount gives an option of counting CJK characters.

**Comment by Aerijo** [comment]
@shuntaroy I've released a setting which allows you to specify options that are then passed directly to every texcount command. They are appended just before the file path, so they will override any options placed there by default (e.g., the `-merge` in document wordcount will be ignored if your options contains `-noinc`).

With regards to the verbose output, there is currently no support for it. For now, if you would like to see it, I suggest installing a package like `platformio-ide-terminal` (it works as a standalone terminal; I had trouble getting alternatives to work), and running the command from there.

**Comment by shuntaroy** [comment]
@Aerijo Thank you for your super fast update! It works fine!

In fact, formerly I had executed texcount directly from `platformio-ide-terminal` to have word counts, but after finding your package, to instantly check word stats have become very easy.
So I am grateful for your development!
